- db/migrations/20210823204648-create-pawment.js
- db/models/pawment.js
- db/models/pawst.js
- db/models/user.js
new pull request to merge created pawment migration/model file!
> created pawment table

- db/migrations/20210823211949-create-catnip.js
- db/models/catnip.js
- db/models/pawst.js
- db/models/user.js
> Added Catnips

- db/models/pawst.js
- db/models/user.js
Fixed typo on User.js and Pawst.js.
> fixed typo

- package-lock.json
- package.json
- public/stylesheets/reset.css
- routes/users.js
- routes/utils.js
- views/layout.pug
- views/user-signup.pug
- views/utils.pug
Started working on the routes for users and started editing the pug.
> Authentication

- package-lock.json
- package.json
- routes/users.js
- views/user-signup.pug
- views/utils.pug
> prog on signup/post

- package-lock.json
- routes/users.js
- views/layout.pug
- views/user-login.pug
- views/user-signup.pug
Completed implementing the logout functionality and refined the styling for the login, logout, and signup buttons.
> Finished implementing logout functionality and some styling

- app.js
- routes/pawsts.js
- routes/users.js
- views/layout.pug
- views/new-pawst.pug
- views/user-page.pug
- views/utils.pug
made progress on pawsts/user feed
> Pawst creation

- routes/index.js
- views/index.pug
- views/user-page.pug
Created homepage/index js and pug files. Implemented functionality.
> Homepage create

- routes/pawsts.js
- views/pawst.pug
> Completed delete route

- db/seeders/20210823195823-Users.js
- db/seeders/20210825024731-Pawsts.js
I created a few users seed, so we can all have the same users and not have to create different users on our local machines.
> User seeder branch

- public/stylesheets/login.css
- public/stylesheets/main.css
- public/stylesheets/new-pawst.css
- public/stylesheets/signup.css
- views/edit-pawst.pug
- views/layout.pug
- views/new-pawst.pug
- views/user-login.pug
- views/user-signup.pug
Added routes for edit and posts.  Merged changed files.
> added some basic styling for a few more pages

- views/pawst.pug
Fixed bug where unauthenticated user cannot see posts without throwing an error.
> fixed minor bug

- public/javascripts/index.js
Fixed error where logged out user would see an error message saying cannot call 'addEventListener' to null
> fixed console error for logged out user when viewing a pawst page

- public/javascripts/index.js
- public/javascripts/pawsts.js
- public/stylesheets/index.css
- public/stylesheets/main.css
- public/stylesheets/user-page.css
- routes/index.js
- routes/users.js
- views/index.pug
- views/pawst.pug
changed spacing and font sizes
> Users home page branch kenneth

- public/stylesheets/edit-pawst.css
- public/stylesheets/index.css
- public/stylesheets/login.css
- public/stylesheets/main.css
- public/stylesheets/new-pawst.css
- public/stylesheets/pawst.css
- public/stylesheets/signup.css
Minor logo adjustments on the navbar
> minor logo adjustments

- README.md
- package-lock.json
- package.json
All sections of README are drafted, feel free to edit as you see fit to accurately represent your experience on this project!
> Readme branch

- public/stylesheets/index.css
- public/stylesheets/main.css
- views/index.pug
Added some styling to rotating pun header on main page. --Not married to this at all. Please edit/remove as the group sees fit.--
> Main title css branch

- public/stylesheets/main.css
- routes/api/apis.js
> Styling issues

- routes/users.js
> fixed minor validation errors

- routes/users.js
another minor change! for password validator!
> changed loginvalidator for password msg

- public/javascripts/index.js
- public/stylesheets/pawst.css
Cleaned up some of the CSS and added a few tweaks for shifting link hovers.
> Added fix for catnip toggle and a couple of language lines

- public/stylesheets/pawst.css
- views/pawst.pug
Add a basic conditional render and seperation of css styling for the catnips btn for the purpose of being more intuitive on what a logged OUT user can and can't do.
> conditional rendering of catnips div(s) for logged in/out user

- public/javascripts/pawsts.js
- public/stylesheets/login.css
- public/stylesheets/new-pawst.css
- public/stylesheets/pawst.css
- public/stylesheets/signup.css
- public/stylesheets/splash.css
- views/splash.pug
- updated "here" a tags on splash page to stand out more.
- darkened focus on pawments when editing (note: the original plan was to focus ON click of the edit button, but currently this only works for newly created pawments. need to figure out a way to affect existing pawments as well.)
- re-added accent color to input fields
> Minor changes
